### ISSUE TITLE
Add examples of working configurations to README

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [irreleph4nt/mkinitcpio-bluetooth#10]
Hi, Thank you for this nice hook. After giving up a few times I finally got it working...

Perhaps you would like to add some examples to the README for inspiration for other people?

e.g. For my Logitech K380 I needed `hidp`, for the Qualcomm Bluetooth card (AX500) I needed only `hci_uart` but for enabling the UART I needed both `intel_lpss_pci` and `8250_dw` (because the AX500 is directly attached to the UART of the system instead of USB...) and two firmware files:

```
/lib/firmware/qca/htbtfw20.tlv
/lib/firmware/qca/htnv20.bin
```

Thanks again!

**Comment by irreleph4nt** [comment]
Hi and thank you for your feedback! I'd be happy to take such a thing on board but this will require a well thought out table or page design. Ideally, we'd want to keep things easy to understand so people know whether their device combinations have been tried before. Alternatively, I could also see this as a wiki page where we divide into individual sections specific to keyboards and BT adapters, listing requirements for each. If you want to create a pull request for this I'd be happy to merge it.

**Comment by h3x4d3c1m4l** [comment]
Hi, Sorry I completely forgot to reply.

Unfortunately I don't have this notebook anymore :(
