### ISSUE TITLE
bluetooth: hci0: Hardware Error 0x58

### ISSUE THREAD

**Issue by ghost** [irreleph4nt/mkinitcpio-bluetooth#14]
Connected, paired & trusted device. Hooked `bluetooth` into `mkinitcpio` & re-ran `mkinitcpio -P`.
On boot up, systemd waits for sometime to connect to bluetooth, & then suddenly
`bluetooth: hci0: Hardware Error 0x58`

**Comment by andimattes** [comment]
Same for me, unfortunately I haven't found any fix for that

**Comment by irreleph4nt** [comment]
I am not able to reproduce this issue unfortunately. From an extended Google search, `Error 0x58` refers to a large and vast bucket of all kinds of issues related to bluetooth. I came across device failure, driver as well as protocol issues. The latter can be solved disabling the ERTM feature in your kernel (ref. [gnome mailing list](https://bugs.launchpad.net/gnome-control-center/+bug/1750146)), but I have doubts this will help with initramfs issues.
