### ISSUE TITLE
The HOOK disables the Bluetooth

### ISSUE THREAD

**Issue by nikolaof** [irreleph4nt/mkinitcpio-bluetooth#15]
Once I enable the bluetooth HOOK as docs suggests, on boot the bluetooth is killed.
rfkill list returns that it is killed by software.
Is there any explanation?

**Comment by irreleph4nt** [comment]
Hi @nikolaof. In case this is still an issue, kindly troubleshoot and provide information related to bluetooth obtained from the system journal as well as dmesg. In general however, it is not uncommon that bluetooth disconnects in between boot (after password was entered) and login. If you reuse the same bluetooth profile for your device as suggested in the README, then your keyboard should be reconnecting on its own.
