### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by DucNg** [irreleph4nt/mkinitcpio-bluetooth#8]
I'm trying to get this to work but I can't figure out what's wrong.

I've installed required packages, I've change my hooks to:
`HOOKS=(base udev keyboard keymap bluetooth autodetect modconf block encrypt lvm2 filesystems fsck)`

`AutoEnable=true` is enabled and works perfectly fine once the system is booted.

My root partition is encrypted but not /boot. When I boot my system for the first time, bluetooth isn't working unless I suspend and then wake up. I suspect that something is going wrong with bluetooth in the boot process but I can't figure out what. I don't know what to look for in journalctl.

**Comment by irreleph4nt** [comment]
At first glance this screams "firmware missing in kernel image" to me. Can you please look for "bluetooth" in **both** dmesg output as well as the journal and paste the results here or upload to a safe pastebin?
Bear in mind please that I am no longer using Arch, so the help I can provide is limited.

**Comment by DucNg** [comment]
You're probably right. Here is log from boot:

journalctl
```
Oct 26 09:19:24 duc-manjaro kernel: random: bluetoothd: uninitialized urandom read (4 bytes read)
Oct 26 09:19:24 duc-manjaro kernel: bluetooth hci0: Direct firmware load for intel/ibt-20-1-3.sfi failed with error -2
Oct 26 09:19:26 duc-manjaro NetworkManager[571]: <info>  [1635232766.4541] Loaded device plugin: NMBluezManager (/usr/lib/NetworkManager/1.32.12-1/libnm-device-plugin-bluetooth.so)
Oct 26 09:19:26 duc-manjaro bluetoothd[669]: Bluetooth daemon 5.61
Oct 26 09:19:26 duc-manjaro audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 26 09:19:26 duc-manjaro bluetoothd[669]: Starting SDP server
Oct 26 09:19:26 duc-manjaro bluetoothd[669]: Bluetooth management interface 1.18 initialized
Oct 26 09:20:09 duc-manjaro bluetoothd[669]: Endpoint registered: sender=:1.26 path=/MediaEndpoint/A2DPSink/sbc
Oct 26 09:20:09 duc-manjaro bluetoothd[669]: Endpoint registered: sender=:1.26 path=/MediaEndpoint/A2DPSource/sbc
Oct 26 09:20:09 duc-manjaro bluetoothd[669]: Endpoint registered: sender=:1.26 path=/MediaEndpoint/A2DPSink/sbc_xq_453
Oct 26 09:20:09 duc-manjaro bluetoothd[669]: Endpoint registered: sender=:1.26 path=/MediaEndpoint/A2DPSource/sbc_xq_453
Oct 26 09:20:09 duc-manjaro bluetoothd[669]: Endpoint registered: sender=:1.26 path=/MediaEndpoint/A2DPSink/sbc_xq_512
Oct 26 09:20:09 duc-manjaro bluetoothd[669]: Endpoint registered: sender=:1.26 path=/MediaEndpoint/A2DPSource/sbc_xq_512
Oct 26 09:20:09 duc-manjaro bluetoothd[669]: Endpoint registered: sender=:1.26 path=/MediaEndpoint/A2DPSink/sbc_xq_552
Oct 26 09:20:09 duc-manjaro bluetoothd[669]: Endpoint registered: sender=:1.26 path=/MediaEndpoint/A2DPSource/sbc_xq_552
Oct 26 09:20:09 duc-manjaro kernel: input: Keychron K2 Keyboard as /devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:256/0005:05AC:0250.0004/input/input35
Oct 26 09:20:09 duc-manjaro kernel: input: Keychron K2 Consumer Control as /devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:256/0005:05AC:0250.0004/input/input36
Oct 26 09:20:09 duc-manjaro kernel: input: Keychron K2 System Control as /devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:256/0005:05AC:0250.0004/input/input37
Oct 26 09:20:09 duc-manjaro kernel: input: Keychron K2 as /devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:256/0005:05AC:0250.0004/input/input39
Oct 26 12:48:26 duc-manjaro kernel: input: Keychron K2 as /devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:256/0005:05AC:0250.0007/input/input42
Oct 26 12:48:26 duc-manjaro upowerd[5393]: treating change event as add on /sys/devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:256/0005:05AC:0250.0007/power_supply/hid-dc:2c:26:f3:6c:9b-battery
```

dmesg
```
[    1.342575] random: bluetoothd: uninitialized urandom read (4 bytes read)
[    1.717123] bluetooth hci0: Direct firmware load for intel/ibt-20-1-3.sfi failed with error -2
[   57.115523] input: Keychron K2 Keyboard as /devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:256/0005:05AC:0250.0004/input/input35
[   57.115739] input: Keychron K2 Consumer Control as /devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:256/0005:05AC:0250.0004/input/input36
[   57.115798] input: Keychron K2 System Control as /devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:256/0005:05AC:0250.0004/input/input37
[   57.330139] input: Keychron K2 as /devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:256/0005:05AC:0250.0004/input/input39
```

I guess the intersting part is: `Direct firmware load for intel/ibt-20-1-3.sfi failed with error -2`
How do I get this to work?

EDIT: I'll try adding `btusb` to MODULES

**Comment by irreleph4nt** [comment]
We've had another user with similar problems before, so please also review what I wrote here: [Issue 6 Comment](https://github.com/irreleph4nt/mkinitcpio-bluetooth/issues/6#issuecomment-734281741)

Someone else also commented on AUR that they had to include an additional module. 
In general, the problem can be boiled down to...

1. Make sure firmware is loaded during boot (keep in mind clean FW reloads happen only upon shutdown, not on restart, sleep or hibernate)
2. Make sure all other relevant modules / executables are in initramfs that your specific BT adapter depends on
3. If 1 & 2 are present, try to rule out your BT adapter and its (potentially bad) driver causing the problem

I am limited in how much I can assist you here. What BT adapter are you using?

**Comment by DucNg** [comment]
I'm using Intel Corp. AX200 Bluetooth build in my laptop which is supported by iwlwifi module.

iwlwifi doesn't seem to support loading early so I guess I'm stuck on step 2?

Adding iwlwifi to MODULES doesn't work and I don't even have wifi after boot.

Can I try anything else?

**Comment by irreleph4nt** [comment]
In similar cases, people have checked that the apropriate linux-firmware package is installed on their system. I assume your bluetooth was working even before you tried using this hook? If so, the firmware is installed but you may have to include the actual firmware file mentioned in the error message at the exact location mentioned inside initramfs. This way, during boot the file would be found and loaded, I assume.

**Comment by DucNg** [comment]
Yes that was exactly it! Thanks a lot! I now understand how mkinitcpio actually works. 

I edited mkinitcpio and added:
`FILES=(/usr/lib/firmware/intel/ibt-20-1-3.sfi)`

I'll modify README to add my findings.
